import{a as S,S as $,i}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="50192556-e4befb0963aba9fc8ac0fc72c";async function d(o,r){return(await S.get("https://pixabay.com/api/",{params:{key:v,q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r}})).data}const y=document.querySelector(".gallery"),g=document.querySelector(".loader");let q=new $(".gallery a");const f=document.querySelector(".more-btn");function h(o){const r=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:u,comments:L,downloads:b})=>`<li class="gallery-item">
            <a href="${a}" class="gallery-link">
                <img src="${s}" alt="${e}" class="gallery-image" />
                <p class="gallery-likes">Likes <span>${t}</span></p>
                <p class="gallery-views">Views <span>${u}</span></p>
                <p class="gallery-comments">Comments <span>${L}</span></p>
                <p class="gallery-downloads">Downloads <span>${b}</span></p>
            </a>
        </li>`).join("");y.insertAdjacentHTML("beforeend",r),q.refresh()}function E(){y.innerHTML=""}function p(){g.classList.remove("hidden")}function n(){g.classList.add("hidden")}function w(){f.classList.remove("hidden")}function m(){f.classList.add("hidden")}const P=document.querySelector(".form"),B=document.querySelector(".more-btn");let c,l=1;P.addEventListener("submit",async o=>{if(o.preventDefault(),E(),m(),l=1,c=o.target.elements["search-text"].value.trim(),o.target.elements["search-text"].value="",c==="")return i.error({title:"Error",message:"Sorry, your don't write anything. Please try again!",color:"yellow"});p();try{const r=await d(c,l),s=r.totalHits,a=r.hits;if(a.length===0)return n(),i.warning({title:"Error",message:`Sorry, there are no images matching your search query ${c}. Please try again!`});if(n(),h(a),s<=l*15)return n(),m(),i.info({message:"We're sorry, but you've reached the end of search results."});w(),l++}catch(r){n(),i.error({title:"Error",message:`Something went wrong: ${r.message}`})}});B.addEventListener("click",async o=>{m(),p();try{const r=await d(c,l),s=r.hits,a=r.totalHits,t=document.querySelector(".gallery-item").getBoundingClientRect();if(s.length===0)return n(),i.error({title:"Error",message:`Sorry, there are no images matching your search query ${c}. Please try again!`});if(n(),h(s),a<=l*15)return n(),m(),i.info({message:"We're sorry, but you've reached the end of search results."});window.scrollBy({top:t.height*2,behavior:"smooth"}),l++,w()}catch(r){n(),i.error({title:"Error",message:`Something went wrong: ${r.message}`})}});
//# sourceMappingURL=index.js.map
