import{a as S,S as $,i}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const v="50192556-e4befb0963aba9fc8ac0fc72c";function m(o,r){return S.get("https://pixabay.com/api/",{params:{key:v,q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r}})}const g=document.querySelector(".gallery"),y=document.querySelector(".loader");let q=new $(".gallery a");const f=document.querySelector(".more-btn");function h(o){const r=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:u,comments:L,downloads:b})=>`<li class="gallery-item">
            <a href="${s}" class="gallery-link">
                <img src="${a}" alt="${e}" class="gallery-image" />
                <p class="gallery-likes">Likes <span>${t}</span></p>
                <p class="gallery-views">Views <span>${u}</span></p>
                <p class="gallery-comments">Comments <span>${L}</span></p>
                <p class="gallery-downloads">Downloads <span>${b}</span></p>
            </a>
        </li>`).join("");g.insertAdjacentHTML("beforeend",r),q.refresh()}function E(){g.innerHTML=""}function p(){y.classList.remove("hidden")}function n(){y.classList.add("hidden")}function w(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const P=document.querySelector(".form"),B=document.querySelector(".more-btn");let c,l=1;P.addEventListener("submit",async o=>{if(o.preventDefault(),E(),d(),l=1,c=o.target.elements["search-text"].value.trim(),o.target.elements["search-text"].value="",c==="")return i.error({title:"Error",message:"Sorry, your don't write anything. Please try again!",color:"yellow"});p();try{const r=await m(c,l),a=r.data.totalHits,s=r.data.hits;if(s.length===0)return n(),i.warning({title:"Error",message:`Sorry, there are no images matching your search query ${c}. Please try again!`});if(n(),h(s),a<=l*15)return n(),d(),i.info({message:"We're sorry, but you've reached the end of search results."});w(),l++}catch(r){n(),i.error({title:"Error",message:`Something went wrong: ${r.message}`})}});B.addEventListener("click",async o=>{d(),p();try{const r=await m(c,l),a=r.data.hits,s=r.data.totalHits,t=document.querySelector(".gallery-item").getBoundingClientRect();if(s<=l*15)return n(),d(),i.info({message:"We're sorry, but you've reached the end of search results."});if(a.length===0)return n(),i.error({title:"Error",message:`Sorry, there are no images matching your search query ${c}. Please try again!`});n(),h(a),window.scrollBy({top:t.height*2,behavior:"smooth"}),l++,w()}catch(r){n(),i.error({title:"Error",message:`Something went wrong: ${r.message}`})}});
//# sourceMappingURL=index.js.map
